require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - vendor/**/*
    - config/**/*
    - db/**/*
    - bin/**/*
    - tmp/**/*

Style/MultilineBlockChain:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/MethodLength:
  Exclude:
    - spec/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/PredicateName:
  NamePrefix:
    - is_
    - have_
  ForbiddenPrefixes:
    - is_
    - have_

# Disabled because of fact that interfaces are implicit in Ruby
# It's bad to use `instance_double` for some implementation from separate module
# Because it couples tested code with that module
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/DescribeMethod:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
